# -*- coding: utf-8 -*-
"""nm new 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uODML4TXauEyXVfPNiZVetnBAlKpnTvK
"""

!pip install gTTS

import gradio as gr
import torch, uuid, os
from transformers import AutoTokenizer, AutoModelForCausalLM
from gtts import gTTS

# === Model Setup ===
model_name = "ibm-granite/granite-3.2-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# === Core Response Generator ===
def generate_response(prompt, max_length=512):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
    if torch.cuda.is_available():
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_length=max_length,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    response = response.replace(prompt, "").strip()
    return response

# === Educational Features ===
def concept_explanation(concept):
    prompt = f"Explain the concept of {concept} in detail with examples."
    return generate_response(prompt, max_length=800)

def summarize_topic(topic):
    prompt = f"Summarize the topic '{topic}' in 5-6 bullet points."
    return generate_response(prompt, max_length=500)

def flashcards_generator(topic):
    prompt = f"Generate 5 flashcards for {topic} in 'Question: ... | Answer: ...' format."
    return generate_response(prompt, max_length=600)

def quiz_generator(concept):
    prompt = f"Generate 5 quiz questions about {concept} with different question types (MCQ, True/False, Short Answer)."
    return generate_response(prompt, max_length=1200)

# === Text-to-Speech ===
def text_to_speech(text):
    if not text.strip():
        return None
    file_name = f"tts_{uuid.uuid4().hex}.mp3"
    tts = gTTS(text)
    tts.save(file_name)
    return file_name

# === Save as File ===
def save_as_file(text, filename="output.txt"):
    if not text.strip():
        return None
    with open(filename, "w", encoding="utf-8") as f:
        f.write(text)
    return filename

# === Gradio App ===
with gr.Blocks() as app:
    gr.Markdown("## 🎓 Educational AI Assistant")

    with gr.Tabs():
        # Concept Explanation Tab
        with gr.TabItem("📘 Concept Explanation"):
            concept_input = gr.Textbox(label="Enter a concept", placeholder="e.g., Machine Learning")
            explain_btn = gr.Button("Explain")
            explanation_output = gr.Textbox(label="Explanation", lines=10)
            audio_btn = gr.Button("🔊 Listen")
            file_btn = gr.Button("⬇️ Download Explanation")
            audio_output = gr.Audio()
            file_output = gr.File()

            explain_btn.click(concept_explanation, inputs=concept_input, outputs=explanation_output)
            audio_btn.click(text_to_speech, inputs=explanation_output, outputs=audio_output)
            file_btn.click(save_as_file, inputs=explanation_output, outputs=file_output)

        # Summary Tab
        with gr.TabItem("📑 Summary"):
            summary_input = gr.Textbox(label="Enter a topic", placeholder="e.g., Neural Networks")
            summary_btn = gr.Button("Summarize")
            summary_output = gr.Textbox(label="Summary", lines=8)
            summary_audio_btn = gr.Button("🔊 Listen")
            summary_file_btn = gr.Button("⬇️ Download Summary")
            summary_audio = gr.Audio()
            summary_file = gr.File()

            summary_btn.click(summarize_topic, inputs=summary_input, outputs=summary_output)
            summary_audio_btn.click(text_to_speech, inputs=summary_output, outputs=summary_audio)
            summary_file_btn.click(save_as_file, inputs=summary_output, outputs=summary_file)

        # Flashcards Tab
        with gr.TabItem("🎴 Flashcards"):
            flash_input = gr.Textbox(label="Enter a topic", placeholder="e.g., Chemistry")
            flash_btn = gr.Button("Generate Flashcards")
            flash_output = gr.Textbox(label="Flashcards", lines=12)

            flash_btn.click(flashcards_generator, inputs=flash_input, outputs=flash_output)

        # Quiz Generator Tab
        with gr.TabItem("📝 Quiz Generator"):
            quiz_input = gr.Textbox(label="Enter a topic", placeholder="e.g., Physics")
            quiz_btn = gr.Button("Generate Quiz")
            quiz_output = gr.Textbox(label="Quiz Questions", lines=15)

            quiz_btn.click(quiz_generator, inputs=quiz_input, outputs=quiz_output)

app.launch(share=True)